Repository connect-foundation/2019-07, pull requests merged in 2019-11, with the labels that each got.

#12 Style: server 디렉토리에 airbnb lint 적용
  server/.eslintrc.js
  server/app.js
  server/bin/www
  server/routes/index.js
Labels: refactoring

#13 Feat: 게임 대기실 Player/Host 소켓 통신 구현 완료
  client/package.json
  client/src/Router.js
  client/src/components/inGame/PlayerFooter.js
  client/src/components/inGame/ProgressBar.js
  client/src/pages/MainPage.js
  client/src/pages/host/WaitingRoom.js
  client/src/pages/mainPage/EnterNickname.js
  client/src/pages/mainPage/EnterRoomNumber.js
  client/src/pages/player/WaitingRoom.js
  server/app.js
  server/bin/www
  server/package.json
  server/socket.js
  server/yarn.lock
Labels: backend, frontend, socket

#14 Feat: 방 번호, 닉네임 유효성 결과 라우팅 서버 기능 구현
  server/app.js
  server/deploy/initInMemory.js
  server/models/inMemory.js
  server/models/templates.js
  server/routes/api.js
  server/routes/apis/room.js
  server/routes/apis/user.js
  server/routes/index.js
  server/utils/checkJsonHasKeys.js
Labels: backend, new feature

#18 !Update master branch
  .gitignore
  .vscode/settings.json
  client/.gitignore
  client/.prettierrc
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.js
  client/src/Router.js
  client/src/components/common/ContentSection.js
  client/src/components/common/CopyrightFooter.js
  client/src/components/common/Header.js
  client/src/components/common/MainContainer.js
  client/src/components/common/VerticalAlignContainer.js
  client/src/components/inGame/HostFooter.js
  client/src/components/inGame/PlayerFooter.js
  client/src/components/inGame/ProgressBar.js
  client/src/components/logo/Logo.css
  client/src/components/logo/Logo.js
  client/src/components/mainPage/Background.js
  client/src/constants/colors.js
  client/src/constants/domain.js
  client/src/index.css
  client/src/index.js
  client/src/pages/MainPage.js
  client/src/pages/host/WaitingRoom.js
  client/src/pages/mainPage/EnterNickname.js
  client/src/pages/mainPage/EnterRoomNumber.js
  client/src/pages/player/WaitingRoom.js
  client/src/styles/common.js
  client/yarn.lock
  package.json
  server/.eslintrc.js
  server/.gitignore
  server/.prettierrc
  server/app.js
  server/bin/www
  server/deploy/initInMemory.js
  server/models/inMemory.js
  server/models/templates.js
  server/package-lock.json
  server/package.json
  server/routes/api.js
  server/routes/apis/room.js
  server/routes/apis/user.js
  server/socket.js
  server/utils/checkJsonHasKeys.js
  server/yarn.lock
  yarn.lock
Labels: emergency, release

#20 Design: 모바일 퍼스트형 디자인 반영 및 버튼 기본 스타일 변경
  client/src/components/common/Buttons.js
  client/src/components/common/MainContainer.js
  client/src/components/logo/Logo.css
  client/src/index.css
  client/src/pages/host/WaitingRoom.js
  client/src/pages/mainPage/EnterNickname.js
  client/src/pages/mainPage/EnterRoomNumber.js
  client/src/styles/common.js
Labels: frontend

#26 Docs: 프로젝트 소개 README.md 추가
  README.md
Labels: doc

#25 !HOTFIX: 배포 서버 접속 시 소켓 통신이 되지 않는 현상 수정
  client/dev.env
  client/package.json
  client/src/pages/host/WaitingRoom.js
  client/src/pages/player/WaitingRoom.js
Labels: bug, frontend, socket

#27 !Update master branch
  README.md
  client/dev.env
  client/package.json
  client/src/components/common/Buttons.js
  client/src/components/common/MainContainer.js
  client/src/components/logo/Logo.css
  client/src/index.css
  client/src/pages/host/WaitingRoom.js
  client/src/pages/mainPage/EnterNickname.js
  client/src/pages/mainPage/EnterRoomNumber.js
  client/src/pages/player/WaitingRoom.js
  client/src/styles/common.js
Labels: release

#28 Feat: cors 설정 및 화이트리스트 옵션 추가
  server/app.js
  server/configs/cors.js
  server/dev.env
Labels: backend, new feature

#36 Refactor: client 코드 리팩토링
  client/src/Router.js
  client/src/components/common/Buttons.js
  client/src/components/common/MainContainer.js
  client/src/components/mainPage/EnterNickname.js
  client/src/components/mainPage/EnterRoomNumber.js
  client/src/pages/host/WaitingRoom.js
  client/src/pages/mainPage/MainPage.js
  client/src/pages/player/WaitingRoom.js
Labels: frontend, refactoring

#40 Refactor: 버튼의 오타 수정과 재사용성 고려한 리팩토링
  client/package.json
  client/src/components/common/Buttons.js
  client/src/components/mainPage/EnterNickname.js
  client/src/components/mainPage/EnterRoomNumber.js
  client/src/index.css
  client/src/pages/host/WaitingRoom.js
Labels: refactoring

#41 Feat: server측 api 요청에 따른 방 번호, 닉네임 유효성 검사
  server/routes/apis/room.js
  server/routes/apis/user.js
Labels: backend, new feature

#43 Feat: client측 방 번호, 닉네임 유효성 검사 후 페이지 라우팅 처리
  client/package.json
  client/src/Router.js
  client/src/components/mainPage/EnterNickname.js
  client/src/components/mainPage/EnterRoomNumber.js
  client/src/pages/host/HostWaitingRoom.js
  client/src/pages/player/PlayerWaitingRoom.js
  client/src/utils/fetch.js
  server/app.js
  server/configs/cors.js
  server/deploy/initInMemory.js
  server/dev.env
  server/routes/apis/room.js
  server/routes/apis/user.js
Labels: backend, frontend, new feature, refactoring

#45 Refactor: POST 관련 fetch 모듈화, 줄맞춤 수정
  client/src/components/mainPage/EnterNickname.js
  client/src/components/mainPage/EnterRoomNumber.js
  client/src/utils/fetch.js
Labels: frontend, refactoring

#46 Feat: MainPage 리팩토링, ToastMessage 구현 및 적용, media.js 생성
  client/src/App.js
  client/src/Router.js
  client/src/components/common/Buttons.js
  client/src/components/common/ContentSection.js
  client/src/components/common/MainContainer.js
  client/src/components/common/ToastProvider.js
  client/src/components/common/VerticalAlignContainer.js
  client/src/components/logo/Logo.css
  client/src/components/mainPage/Background.js
  client/src/components/mainPage/EnterNickname.js
  client/src/components/mainPage/EnterRoomNumber.js
  client/src/constants/media.js
  client/src/index.css
  client/src/pages/MainPage.js
  client/src/pages/mainPage/MainPage.js
  client/src/pages/player/PlayerWaitingRoom.js
Labels: frontend, refactoring

#48 Feat: 단일 방 상세 페이지 프론트 기본 동작 구현
  client/src/components/detailRoom/RoomInformation.js
  client/src/components/detailRoom/TabContents.js
  client/src/pages/host/HostDetailRoom.js
Labels: frontend, new feature

#51 Feat: 네이버 oauth 로그인 기능 추가
  client/dev.env
  client/src/Router.js
  client/src/assets/images/naverLoginButton.PNG
  client/src/assets/images/naverLoginButton_long.PNG
  client/src/components/mainPage/NaverLogin.js
  client/src/constants/apiAddresses.js
  client/src/pages/MainPage.js
  client/src/pages/login/CallBackPage.js
  client/src/utils/fetch.js
  client/src/utils/naverLoginSdk.js
  server/package-lock.json
  server/package.json
  server/routes/api.js
  server/routes/apis/login.js
  server/yarn.lock
Labels: backend, frontend, new feature

#53 Feat: 인메모리 구조 변경 및 소켓 통신 기능 업데이트
  client/src/pages/host/HostWaitingRoom.js
  client/src/pages/player/PlayerWaitingRoom.js
  server/app.js
  server/models/inMemory.js
  server/models/rooms.js
  server/models/templates.js
  server/models/templates/player.js
  server/models/templates/quiz.js
  server/models/templates/room.js
  server/routes/apis/room.js
  server/routes/apis/user.js
  server/socket.js
Labels: backend, socket

#54 Fix: 네이버로 로그인 한 뒤 이동하는 페이지 변경
  client/src/constants/apiAddresses.js
  client/src/pages/login/CallBackPage.js
Labels: bug

#56 Design: 헤더 중앙에 서비스 로고 출력 및 헤더에 방 번호 출력
  client/public/static-logo.png
  client/src/components/common/Header.js
  client/src/components/inGame/HostFooter.js
  client/src/pages/host/HostWaitingRoom.js
Labels: frontend

#60 Docs(README): README.md을 개선한 초기 버전 완성
  README.md
  docs/demo1.jpg
Labels: doc

#57 Feat: 퀴즈 편집 페이지 UI 작업 60% 완료
  client/src/Router.js
  client/src/assets/images/checkMark.png
  client/src/components/edit/ItemCard.js
  client/src/components/edit/ScorePicker.js
  client/src/components/edit/TimeLimitPicker.js
  client/src/pages/host/EditPage.js
Labels: frontend, new feature

#59 Feat: 방 상세 페이지 라우팅 추가
  client/src/Router.js
  client/src/constants/apiAddresses.js
Labels: frontend

#61 Fix: 편집 페이지 퀴즈 타이틀에 NaN 문제 해결
  client/src/pages/host/EditPage.js
Labels: bug, frontend

#67 Docs(README): 데일리 스크럼 상세 링크 추가
  README.md
Labels: doc

#68 README 갱신내용 master에 반영
  README.md
Labels: doc

#72 Feat(dotenv): URL의 host 주소 dotenv로 관리하도록 변경
  client/dev.env
  client/src/components/mainPage/NaverLogin.js
  client/src/constants/apiAddresses.js
  server/dev.env
Labels: frontend, release

#77 Refactor(request): request-promise 모듈로 변경
  server/package-lock.json
  server/package.json
  server/routes/apis/login.js
  server/yarn.lock
Labels: refactoring

#78 Refactor: api 형태 post에서 get으로 변경
  README.md
  client/src/constants/apiAddresses.js
  client/src/utils/fetch.js
  server/middleware/validations.js
  server/package-lock.json
  server/package.json
  server/routes/api.js
  server/routes/apis/login.js
  server/routes/apis/room.js
  server/routes/apis/user.js
  server/yarn.lock
Labels: backend, frontend, refactoring

#86 Merge pull request '2ssue:develop' into develop
  server/models/rooms.js
  server/socket.js
Labels: backend, database, socket

#88 Merge pull request 'ocy1011:develop' into develop
  client/src/components/common/ScoreChart.js
Labels: frontend

#89 Merge pull request '2ssue:develop' into develop
  server/models/templates/quiz.js
  server/models/templates/room.js
Labels: database

#91 Merge pull request 'changicho:develop' into develop
  client/package-lock.json
  client/package.json
  client/src/Router.js
  client/src/components/inGame/PlayerHeader.js
  client/src/components/inGame/PlayerQuiz.js
  client/src/components/inGame/PlayerQuizLoading.js
  client/src/components/inGame/PlayerSubResult.js
  client/src/components/inGame/PlayerWaiting.js
  client/src/constants/apiAddresses.js
  client/src/pages/host/HostGameRoom.js
  client/src/pages/host/HostWaitingRoom.js
  client/src/pages/player/PlayerGameRoom.js
  client/src/pages/player/PlayerWaitingRoom.js
  client/src/utils/fetch.js
  client/yarn.lock
  server/deploy/dummy.js
  server/deploy/initInMemory.js
  server/middleware/validations.js
  server/models/dao/__test__/dao.spec.js
  server/models/dao/dao.js
  server/routes/api.js
  server/routes/apis/game.js
Labels: backend, frontend, new feature, socket

#90 Merge pull request 'leecoders:develop' into develop
  client/src/assets/images/emptyImage.png
  client/src/assets/images/transparency.png
  client/src/components/common/Buttons.js
  client/src/components/common/FlexibleInput.js
  client/src/components/edit/EditBody.js
  client/src/components/edit/ItemCard.js
  client/src/components/edit/Preview.js
  client/src/components/edit/ScorePicker.js
  client/src/components/edit/SideBar.js
  client/src/components/edit/Template.js
  client/src/components/edit/TimeLimitPicker.js
  client/src/pages/host/EditPage.js
  client/src/utils/util.js
Labels: frontend, new feature

#92 Feat: Host 퀴즈 진행 페이지 프론트엔드 구현
  client/src/Router.js
  client/src/components/common/ScoreChart.js
  client/src/components/inGame/HostLoading.js
  client/src/components/inGame/HostPlaying.js
  client/src/components/inGame/HostQuizPlayingRoom.js
  client/src/components/inGame/HostSubResult.js
  client/src/components/inGame/HostWaitingRoom.js
  client/src/pages/host/HostGameRoom.js
Labels: frontend

#94 Merge pull request 'changicho:develop' into develop
  client/src/components/inGame/PlayerQuizLoading.js
  client/src/constants/apiAddresses.js
  client/src/pages/player/PlayerGameRoom.js
  client/src/utils/fetch.js
  server/middleware/validations.js
  server/routes/apis/game.js
Labels: backend, emergency, refactoring

#95 Feat: Top 10 Dashboard 출력 페이지 제작
  client/src/components/common/Dashboard.js
  client/src/pages/host/GameResult.js
Labels: frontend, new feature

#97 Merge pull request '2ssue:develop' into develop
  client/src/components/common/ScoreChart.js
  client/src/components/inGame/HostLoading.js
  client/src/components/inGame/HostSubResult.js
  client/src/pages/host/HostGameRoom.js
  client/src/reducer/hostGameReducer.js
  server/models/templates/room.js
Labels: database, frontend, refactoring

#102 Merge pull request '2ssue:develop' into develop
  README.md
Labels: doc

#105 Merge pull request 'ocy1011:develop' into develop
  client/src/Router.js
  client/src/components/common/Header.js
  client/src/components/common/ScoreChart.js
  client/src/components/inGame/HostSubResult.js
  client/src/constants/apiAddresses.js
  client/src/index.css
  client/src/pages/MainPage.js
  client/src/pages/host/SelectRoom.js
  client/src/pages/player/PlayerGameRoom.js
Labels: bug, frontend, refactoring
