Repository connect-foundation/2019-07, pull requests merged in 2019-12, with the labels that each got.

#109 [PR] Feat: database manager 객체 구조
  server/dev.env
  server/models/dao/__test__/dao.spec.js
  server/models/dao/dao.js
  server/models/database/dbManager.js
  server/models/database/tables/Analysis.js
  server/models/database/tables/Item.js
  server/models/database/tables/Quiz.js
  server/models/database/tables/QuizSet.js
  server/models/database/tables/Room.js
  server/models/database/tables/Table.js
  server/models/database/tables/User.js
Labels: backend, database

#110 [PR] Feat: 인게임 리팩토링에 필요한 컴포넌트 추가
  client/src/components/common/LoadingCircle.js
  client/src/components/inGame/Hourglass.js
  client/src/components/inGame/PlayerWaiting.js
Labels: frontend, new feature, refactoring

#112 [PR] Feat: 로그인 시 db에 유저 정보를 저장하는 기능 추가.
  server/constants/tableName.js
  server/models/database/dbManager.js
  server/models/database/tables/Analysis.js
  server/models/database/tables/Item.js
  server/models/database/tables/Quiz.js
  server/models/database/tables/Quizset.js
  server/models/database/tables/Room.js
  server/models/database/tables/User.js
  server/routes/apis/game.js
  server/routes/apis/login.js
Labels: backend, database

#117 [PR]Refactor: 인게임 UI 통일성을 위하여 layout 제작 및 적용
  client/src/components/common/ScoreChart.js
  client/src/components/inGame/HostPlaying.js
  client/src/components/inGame/HostQuizPlayingRoom.js
  client/src/components/inGame/HostSubResult.js
  client/src/components/inGame/Layout.js
  client/src/components/inGame/PlayerFooter.js
  client/src/components/inGame/PlayerQuiz.js
  client/src/components/inGame/PlayerQuizLoading.js
  client/src/pages/player/PlayerGameRoom.js
  client/src/styles/common.js
Labels: frontend, new feature, refactoring

#118 Fix: 한글, 복사 붙여넣기에 대해 입력 제한이 안되는 현상 수정
  client/src/components/common/FlexibleInput.js
Labels: frontend

#119 Feat: Modal 컴포넌트화 구현 완료
  client/src/App.js
  client/src/components/common/Modal.js
  client/src/components/common/ModalProvider.js
Labels: frontend, new feature

#124 Feat: action의 결과값에 따라 Modal을 유지/닫기 할 수 있는 기능 추가
  client/src/components/common/Modal.js
Labels: frontend

#126 Feat: Flexible input Enter Key 입력을 막는 기능 추가 외 1건
  client/src/components/common/FlexibleInput.js
Labels: frontend

#125 [PR] Feat: player 퀴즈 진행시 정답 판별, 점수 갱신, 최종결과 출력 기능 추가
  client/src/components/common/Dashboard.js
  client/src/components/inGame/HostResult.js
  client/src/components/inGame/HostSubResult.js
  client/src/components/inGame/PlayerFooter.js
  client/src/components/inGame/PlayerQuiz.js
  client/src/components/inGame/PlayerResult.js
  client/src/components/inGame/PlayerSubResult.js
  client/src/constants/apiAddresses.js
  client/src/pages/host/HostGameRoom.js
  client/src/pages/player/PlayerGameRoom.js
  client/src/reducer/hostGameReducer.js
  client/src/utils/fetch.js
  server/models/rooms.js
  server/models/templates/quiz.js
  server/models/templates/room.js
  server/routes/apis/game.js
  server/routes/apis/login.js
Labels: backend, frontend, new feature, refactoring

#130 Feat: 방 list 페이지 구현
  client/src/constants/apiAddresses.js
  client/src/pages/host/SelectRoom.js
  client/src/utils/fetch.js
  server/models/database/tables/Room.js
  server/routes/api.js
  server/routes/apis/user.js
Labels: backend, database, frontend

#131 [PR] Feat: 데이터베이스에서 quizset을 가져와 적용하는 기능 추가.
  server/models/database/tables/Quizset.js
  server/models/database/tables/User.js
  server/models/rooms.js
  server/socket.js
Labels: backend, database, new feature

#132 Feat: 방 상세 페이지 기능 구현 (Modal 추가, 백엔드 연동)
  client/src/components/detailRoom/QuizTab.js
  client/src/components/detailRoom/RoomInformation.js
  client/src/components/detailRoom/TabContents.js
  client/src/pages/host/HostDetailRoom.js
  client/src/utils/fetch.js
  server/models/database/tables/Room.js
  server/routes/apis/user.js
Labels: backend, database, frontend

#134 [PR] Fix : URL로 직접접근시 유효하지 않은 경우 처리
  client/src/Router.js
  client/src/pages/NotFoundPage.js
  client/src/pages/player/PlayerGameRoom.js
Labels: bug, frontend, new feature

#139 Feat: Host 인게임 페이지 리팩토링, 최종 점수 출력 기능 구현 및 Player 페이지 버그 수정 외
  client/src/Router.js
  client/src/components/inGame/HostLoading.js
  client/src/components/inGame/HostPlaying.js
  client/src/components/inGame/HostSubResult.js
  client/src/components/inGame/HostWaitingRoom.js
  client/src/components/mainPage/EnterNickname.js
  client/src/pages/Gameover.js
  client/src/pages/NotFoundPage.js
  client/src/pages/host/HostDetailRoom.js
  client/src/pages/host/HostGameRoom.js
  client/src/pages/host/SelectRoom.js
  client/src/pages/player/PlayerGameRoom.js
  client/src/reducer/hostGameReducer.js
  server/deploy/dummy.js
  server/models/templates/room.js
  server/socket.js
Labels: backend, bug, frontend, refactoring

#142 Feat: EditPage 새로 제작
  client/package.json
  client/src/components/common/FlexibleInput.js
  client/src/components/common/Header.js
  client/src/components/edit/EditBody.js
  client/src/components/edit/EditContextProvider.js
  client/src/components/edit/ImageField.js
  client/src/components/edit/Item.js
  client/src/components/edit/ItemCard.js
  client/src/components/edit/ItemContainer.js
  client/src/components/edit/Preview.js
  client/src/components/edit/SideBar.js
  client/src/components/edit/Template.js
  client/src/components/edit/Thumbnail.js
  client/src/components/edit/Title.js
  client/src/pages/host/EditPage.js
  client/src/reducer/hostEditReducer.js
  client/yarn.lock
Labels: frontend, new feature, refactoring

#144 Docs: 5주차 배포에 따른 README 업데이트
  README.md
Labels: doc

#168 Fix: DB 테이블 칼럼에서 order명 변경
  server/models/database/tables/Item.js
  server/models/database/tables/Quizset.js
  server/models/rooms.js
Labels: database

#173 [PR] Fix(database): User를 email 대신 naver id로 구별하도록 변경
  client/src/pages/host/SelectRoom.js
  server/models/database/tables/Room.js
  server/models/database/tables/User.js
  server/routes/apis/login.js
Labels: backend, database

#171 Feat: camelCase <-> snake_case 변환하는 메소드 구현
  client/src/components/common/Loading.js
  client/src/utils/caseChanger.js
Labels: frontend, new feature

#178 !BREAKING CHANGE: 인메모리 구조 변경 외
  client/src/components/mainPage/NaverLogin.js
  client/src/constants/apiAddresses.js
  client/src/pages/login/CallBackPage.js
  client/src/utils/fetch.js
  server/middleware/validations.js
  server/models/inMemory.js
  server/models/rooms.js
  server/models/templates/player.js
  server/models/templates/room.js
  server/routes/apis/game.js
  server/socket.js
Labels: backend, database, refactoring, socket

#180 [PR] Player 퀴즈 진행 API 통합, 최종 결과 페이지에서 Prompt, event 제거
  client/src/components/inGame/PlayerQuiz.js
  client/src/components/inGame/PlayerQuizLoading.js
  client/src/components/inGame/PlayerResult.js
  client/src/components/inGame/PlayerSubResult.js
  client/src/components/mainPage/NaverLogin.js
  client/src/pages/login/CallBackPage.js
  client/src/pages/player/PlayerGameRoom.js
  client/src/utils/fetch.js
  server/models/rooms.js
  server/routes/apis/game.js
  server/routes/apis/login.js
Labels: backend, frontend, refactoring

#185 [PR] Fix: FlexibleInput에서 한글을입력할 때 생기는 오류 제거
  client/src/components/common/FlexibleInput.js
Labels: 😢bug

#183 Feat: 방을 삭제하는 기능 추가 외
  client/src/assets/images/deleteButton.png
  client/src/components/selectRoom/RoomList.js
  client/src/pages/host/SelectRoom.js
  client/src/utils/fetch.js
  server/models/database/tables/Room.js
  server/routes/apis/user.js
Labels: backend, database, frontend, refactoring

#187 Feat: Host 인게임 페이지 리팩토링 및 UX 적 기능 추가
  client/src/components/inGame/HostLoading.js
  client/src/components/inGame/HostPlaying.js
  client/src/components/inGame/HostQuizPlayingRoom.js
  client/src/components/inGame/HostResult.js
  client/src/components/inGame/HostSubResult.js
  client/src/components/inGame/HostWaitingRoom.js
  client/src/pages/host/HostGameRoom.js
  client/src/reducer/hostGameReducer.js
Labels: frontend, refactoring

#186 Feat: EditPage에서 사용하는 api 구현
  client/src/components/mainPage/NaverLogin.js
  client/src/utils/fetch.js
  server/models/database/tables/Item.js
  server/models/database/tables/Quiz.js
  server/models/database/tables/Quizset.js
  server/routes/api.js
  server/routes/apis/edit.js
  server/routes/apis/room.js
Labels: backend, database, frontend, new feature

#191 Feat: EditPage API와 연결되는 프론트 구현
  client/src/components/detailRoom/QuizTab.js
  client/src/components/detailRoom/TabContents.js
  client/src/components/edit/ImageField.js
  client/src/components/edit/Item.js
  client/src/components/edit/SaveButton.js
  client/src/components/edit/Section.js
  client/src/components/edit/SideBar.js
  client/src/components/edit/Thumbnail.js
  client/src/components/edit/Title.js
  client/src/pages/host/EditPage.js
  client/src/pages/host/HostDetailRoom.js
  client/src/reducer/hostEditReducer.js
Labels: frontend, new feature, refactoring

#189 Design: Host 인게임 페이지 버튼 디자인 삭제 및 변경
  client/src/components/common/Buttons.js
  client/src/components/common/Header.js
  client/src/components/detailRoom/RoomInformation.js
  client/src/components/inGame/HostQuizPlayingRoom.js
  client/src/constants/domain.js
Labels: frontend

#194 [PR] Design: 모바일 페이지를 고려한 디자인, 게임 중간 퇴장시 생기는 오류 해결
  client/src/components/common/Dashboard.js
  client/src/components/inGame/HostResult.js
  client/src/components/inGame/HostWaitingRoom.js
  client/src/components/inGame/PlayerQuiz.js
  client/src/components/inGame/PlayerQuizLoading.js
  client/src/components/inGame/PlayerResult.js
  client/src/components/inGame/PlayerWaiting.js
  client/src/components/inGame/PlayerWarning.js
  client/src/pages/player/PlayerGameRoom.js
  client/src/styles/common.js
  server/models/rooms.js
  server/routes/apis/game.js
  server/socket.js
Labels: 😢bug

#195 Feat: 방 상세 페이지 퀴즈 데이터 관련 기능 추가 및 호스트 인게임 이미지 출력
  client/src/assets/images/edit_room.png
  client/src/assets/images/multiple_choice.svg
  client/src/components/detailRoom/QuizList.js
  client/src/components/detailRoom/QuizTab.js
  client/src/components/detailRoom/RoomInformation.js
  client/src/components/detailRoom/TabContents.js
  client/src/components/inGame/HostPlaying.js
  client/src/pages/host/HostDetailRoom.js
Labels: frontend

#200 [PR] Feat: 퀴즈 이미지 추가
  client/src/components/inGame/PlayerQuiz.js
  server/models/database/tables/Quizset.js
  server/models/rooms.js
Labels: backend

#202 [PR] 오브젝트 스토리지 연동
  client/src/components/edit/EditContextProvider.js
  client/src/components/edit/ImageField.js
  client/src/components/edit/SaveButton.js
  client/src/components/edit/Section.js
  client/src/reducer/hostEditReducer.js
  client/src/utils/fetch.js
  server/dev.env
  server/models/database/tables/Quiz.js
  server/objectStorage.js
  server/package.json
  server/routes/apis/edit.js
  server/yarn.lock
Labels: backend, database, frontend, new feature

#203 Design: 파비콘 변경
  client/public/favicon.ico
Labels: frontend

#207 [PR] 배포 후 치명적인 버그를 발견해서 수정함
  client/src/components/edit/Section.js
  client/src/components/edit/SideBar.js
  client/src/reducer/hostEditReducer.js
Labels: frontend, 😢bug

#208 !HOTFIX: 문항 수가 4개가 아닐 때 4개로 출력되는 현상 수정
  client/src/components/common/ScoreChart.js
  client/src/components/inGame/HostQuizPlayingRoom.js
Labels: frontend, 😢bug

#210 [PR] !HOTFIX: 문항 수가 4개가 아닐 때 4개로 출력되는 현상 수정
  client/src/components/inGame/PlayerQuiz.js
Labels: frontend, 😢bug

#224 Merge pull request '2ssue:develop' into develop
  client/src/pages/host/SelectRoom.js
  client/src/utils/util.js
  server/models/rooms.js
  server/socket.js
Labels: backend, frontend

#223 [PR] Design: Player Host 인게임 디자인 수정 외
  client/dev.env
  client/src/components/common/Buttons.js
  client/src/components/common/Loading.js
  client/src/components/common/ScoreChart.js
  client/src/components/inGame/HostPlaying.js
  client/src/components/inGame/HostSubResult.js
  client/src/components/inGame/HostWaitingRoom.js
  client/src/components/inGame/Layout.js
  client/src/components/inGame/PlayerQuiz.js
  client/src/components/inGame/PlayerResult.js
  client/src/components/inGame/PlayerSubResult.js
  client/src/components/inGame/PlayerWaiting.js
  client/src/components/mainPage/NaverLogin.js
  client/src/pages/login/CallBackPage.js
  client/src/pages/player/PlayerGameRoom.js
Labels: backend, frontend

#228 Merge pull request #228 from 2ssue/develop
  client/src/components/detailRoom/RoomInformation.js
  client/src/components/mainPage/EnterNickname.js
  client/src/components/mainPage/EnterRoomNumber.js
  client/src/components/selectRoom/RoomList.js
  client/src/pages/host/HostDetailRoom.js
  client/src/pages/host/SelectRoom.js
  client/src/utils/fetch.js
  server/middleware/validations.js
  server/routes/apis/edit.js
  server/routes/apis/room.js
  server/routes/apis/user.js
Labels: backend, frontend, refactoring, 😢bug

#233 Fix: Modal Flexible Input 이전 값이 그대로 저장되어 있는 이슈 수정 외 리팩토링
  client/src/components/common/FlexibleInput.js
  client/src/components/common/Loading.js
  client/src/components/common/Modal.js
  client/src/components/common/ModalProvider.js
  client/src/components/inGame/HostLoading.js
  client/src/components/inGame/HostResult.js
  client/src/components/inGame/HostWaitingRoom.js
  client/src/components/mainPage/EnterNickname.js
  client/src/pages/host/HostGameRoom.js
Labels: frontend, 😢bug

#237 [PR] Fix: nginx proxy 설정을 위한 api 호출 주소 변경
  client/src/utils/fetch.js
  server/app.js
  server/models/database/tables/Quizset.js
  server/models/rooms.js
  server/routes/api.js
  server/routes/apis/game.js
  server/routes/apis/login.js
  server/routes/apis/room.js
  server/routes/apis/user.js
Labels: backend

#239 Fix: EditPage에서 1번째 퀴즈 타이틀이 사라지는 현상 수정
  client/src/components/common/FlexibleInput.js
Labels: frontend, 😢bug

#240 !HOTFIX: Flexible Input 새로운 입력이 안먹히는 이슈 수정
  client/src/components/common/FlexibleInput.js
Labels: frontend, 😢bug

#234 [PR] 퀴즈 편집 페이지 새로운 기능 추가
  client/src/assets/images/trash.png
  client/src/components/common/Header.js
  client/src/components/edit/ImageField.js
  client/src/components/edit/Item.js
  client/src/components/edit/OptionPanel.js
  client/src/components/edit/RangeInput.js
  client/src/components/edit/SaveButton.js
  client/src/components/edit/Section.js
  client/src/components/edit/SideBar.js
  client/src/pages/host/EditPage.js
  client/src/reducer/hostEditReducer.js
  server/objectStorage.js
  server/routes/apis/edit.js
Labels: backend, frontend, refactoring

#242 Fix: InMemory의 방을 삭제하면서 에러가 발생하는 현상 수정
  client/src/pages/host/HostGameRoom.js
  server/models/rooms.js
  server/socket.js
Labels: backend, 😢bug

#243 [PR] HostWaitingRoom 리팩토링
  client/src/components/common/Loading.js
  client/src/components/inGame/HostFooter.js
  client/src/components/inGame/HostWaitingRoom.js
  client/src/pages/host/HostGameRoom.js
Labels: frontend, refactoring

#244 Fix: 0점일 때 DashBoard에서 점수가 올라가는 현상 수정
  client/src/components/common/Dashboard.js
Labels: frontend

#245 [PR] 마지막 기능 개발
  client/src/Router.js
  client/src/assets/images/click.png
  client/src/assets/images/edit_room.png
  client/src/components/common/GoBackButton.js
  client/src/components/common/Header.js
  client/src/components/common/InformationArea.js
  client/src/components/common/MainContainer.js
  client/src/components/detailRoom/QuizList.js
  client/src/components/detailRoom/QuizTab.js
  client/src/components/detailRoom/RoomInformation.js
  client/src/components/detailRoom/TabContents.js
  client/src/components/edit/SaveButton.js
  client/src/components/edit/Thumbnail.js
  client/src/components/inGame/HostFooter.js
  client/src/components/inGame/HostWaitingRoom.js
  client/src/components/mainPage/EnterNickname.js
  client/src/components/mainPage/EnterRoomNumber.js
  client/src/components/selectRoom/RoomList.js
  client/src/pages/MainPage.js
  client/src/pages/host/EditPage.js
  client/src/pages/host/HostDetailRoom.js
  client/src/pages/host/HostGameRoom.js
  client/src/pages/host/SelectRoom.js
  client/src/pages/login/CallBackPage.js
  client/src/pages/player/PlayerGameRoom.js
Labels: frontend, new feature, refactoring

#247 Feat: 퀴즈 데이터를 불러올 때 Loading 창이 뜨도록 기능 추가 외
  client/src/components/common/CopyrightFooter.js
  client/src/components/detailRoom/QuizTab.js
  client/src/components/edit/SaveButton.js
  client/src/pages/host/HostDetailRoom.js
  client/src/pages/host/SelectRoom.js
  client/src/pages/login/CallBackPage.js
Labels: frontend

#249 [PR] Design: login 버튼 크기 변경
  client/src/assets/images/naverLoginButton_long.PNG
  client/src/components/mainPage/NaverLogin.js
Labels: frontend

#250 [PR] 핫픽스
  client/src/components/inGame/HostFooter.js
  client/src/components/inGame/HostQuizPlayingRoom.js
  client/src/components/inGame/HostResult.js
  client/src/components/inGame/PlayerResult.js
Labels: emergency, frontend, refactoring, 😢bug

#251 [PR] !HOTFIX 버그 수정
  client/src/components/inGame/HostResult.js
  client/src/components/mainPage/EnterRoomNumber.js
  client/src/pages/login/CallBackPage.js
Labels: frontend, 😢bug

#252 [PR] Fix: 플레이어 로딩 문구 변경
  client/src/components/inGame/PlayerQuizLoading.js
Labels: frontend

#254 [PR] Docs: 최종 README 작성
  README.md
  docs/demo1.jpg
  docs/logogif.gif
  docs/structure.png
  docs/technology_stack.png
  docs/thumbnail.gif
Labels: doc

#253 [PR] 인게임 기능개선
  server/models/rooms.js
  server/models/templates/room.js
  server/routes/apis/game.js
Labels: backend, new feature

#256 !HOTFIX: 새로고침, 창닫기와 관련된 이슈 수정
  client/src/components/inGame/PlayerSubResult.js
  client/src/components/mainPage/EnterRoomNumber.js
  client/src/pages/host/HostGameRoom.js
  client/src/pages/player/PlayerGameRoom.js
  server/models/rooms.js
  server/models/templates/room.js
  server/socket.js
Labels: backend, frontend, refactoring, 😢bug

#257 [PR] HOTFIX
  client/src/components/detailRoom/QuizTab.js
  client/src/components/edit/ImageField.js
  client/src/components/edit/ScorePicker.js
  client/src/components/inGame/Layout.js
  client/src/components/inGame/PlayerHeader.js
  client/src/reducer/hostEditReducer.js
  client/src/reducer/hostGameReducer.js
  server/models/rooms.js
  server/models/templates/room.js
  server/routes/apis/game.js
  server/socket.js
Labels: backend, frontend, new feature, refactoring, 😢bug

#258 Feat: 중간에 들어온 플레이어를 나중에 추가되도록 하는 기능 추가
  server/models/rooms.js
  server/models/templates/room.js
  server/socket.js
Labels: backend, socket

#259 [PR] 모바일 환경에서 잘 안보이는 글자 크기 확대
  client/src/components/edit/SideBar.js
  client/src/components/inGame/Layout.js
Labels: frontend

#261 !HOTFIX: 퀴즈가 없을 때 퀴즈 생성이 안되는 문제 수정
  client/src/components/detailRoom/QuizTab.js
  client/src/pages/login/CallBackPage.js
Labels: frontend, 😢bug
